package com.za.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ZaFunctionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public ZaFunctionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFuncIdIsNull() {
            addCriterion("FUNC_ID is null");
            return (Criteria) this;
        }

        public Criteria andFuncIdIsNotNull() {
            addCriterion("FUNC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFuncIdEqualTo(String value) {
            addCriterion("FUNC_ID =", value, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdNotEqualTo(String value) {
            addCriterion("FUNC_ID <>", value, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdGreaterThan(String value) {
            addCriterion("FUNC_ID >", value, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdGreaterThanOrEqualTo(String value) {
            addCriterion("FUNC_ID >=", value, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdLessThan(String value) {
            addCriterion("FUNC_ID <", value, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdLessThanOrEqualTo(String value) {
            addCriterion("FUNC_ID <=", value, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdLike(String value) {
            addCriterion("FUNC_ID like", value, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdNotLike(String value) {
            addCriterion("FUNC_ID not like", value, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdIn(List<String> values) {
            addCriterion("FUNC_ID in", values, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdNotIn(List<String> values) {
            addCriterion("FUNC_ID not in", values, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdBetween(String value1, String value2) {
            addCriterion("FUNC_ID between", value1, value2, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncIdNotBetween(String value1, String value2) {
            addCriterion("FUNC_ID not between", value1, value2, "funcId");
            return (Criteria) this;
        }

        public Criteria andFuncCodeIsNull() {
            addCriterion("FUNC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFuncCodeIsNotNull() {
            addCriterion("FUNC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFuncCodeEqualTo(String value) {
            addCriterion("FUNC_CODE =", value, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeNotEqualTo(String value) {
            addCriterion("FUNC_CODE <>", value, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeGreaterThan(String value) {
            addCriterion("FUNC_CODE >", value, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNC_CODE >=", value, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeLessThan(String value) {
            addCriterion("FUNC_CODE <", value, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeLessThanOrEqualTo(String value) {
            addCriterion("FUNC_CODE <=", value, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeLike(String value) {
            addCriterion("FUNC_CODE like", value, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeNotLike(String value) {
            addCriterion("FUNC_CODE not like", value, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeIn(List<String> values) {
            addCriterion("FUNC_CODE in", values, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeNotIn(List<String> values) {
            addCriterion("FUNC_CODE not in", values, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeBetween(String value1, String value2) {
            addCriterion("FUNC_CODE between", value1, value2, "funcCode");
            return (Criteria) this;
        }

        public Criteria andFuncCodeNotBetween(String value1, String value2) {
            addCriterion("FUNC_CODE not between", value1, value2, "funcCode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("PARENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("PARENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(String value) {
            addCriterion("PARENT_ID =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(String value) {
            addCriterion("PARENT_ID <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(String value) {
            addCriterion("PARENT_ID >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_ID >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(String value) {
            addCriterion("PARENT_ID <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(String value) {
            addCriterion("PARENT_ID <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLike(String value) {
            addCriterion("PARENT_ID like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotLike(String value) {
            addCriterion("PARENT_ID not like", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<String> values) {
            addCriterion("PARENT_ID in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<String> values) {
            addCriterion("PARENT_ID not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(String value1, String value2) {
            addCriterion("PARENT_ID between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(String value1, String value2) {
            addCriterion("PARENT_ID not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andFuncLevelIsNull() {
            addCriterion("FUNC_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andFuncLevelIsNotNull() {
            addCriterion("FUNC_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andFuncLevelEqualTo(Long value) {
            addCriterion("FUNC_LEVEL =", value, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelNotEqualTo(Long value) {
            addCriterion("FUNC_LEVEL <>", value, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelGreaterThan(Long value) {
            addCriterion("FUNC_LEVEL >", value, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelGreaterThanOrEqualTo(Long value) {
            addCriterion("FUNC_LEVEL >=", value, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelLessThan(Long value) {
            addCriterion("FUNC_LEVEL <", value, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelLessThanOrEqualTo(Long value) {
            addCriterion("FUNC_LEVEL <=", value, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelIn(List<Long> values) {
            addCriterion("FUNC_LEVEL in", values, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelNotIn(List<Long> values) {
            addCriterion("FUNC_LEVEL not in", values, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelBetween(Long value1, Long value2) {
            addCriterion("FUNC_LEVEL between", value1, value2, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFuncLevelNotBetween(Long value1, Long value2) {
            addCriterion("FUNC_LEVEL not between", value1, value2, "funcLevel");
            return (Criteria) this;
        }

        public Criteria andFunSeqIsNull() {
            addCriterion("FUN_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andFunSeqIsNotNull() {
            addCriterion("FUN_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andFunSeqEqualTo(Long value) {
            addCriterion("FUN_SEQ =", value, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqNotEqualTo(Long value) {
            addCriterion("FUN_SEQ <>", value, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqGreaterThan(Long value) {
            addCriterion("FUN_SEQ >", value, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqGreaterThanOrEqualTo(Long value) {
            addCriterion("FUN_SEQ >=", value, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqLessThan(Long value) {
            addCriterion("FUN_SEQ <", value, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqLessThanOrEqualTo(Long value) {
            addCriterion("FUN_SEQ <=", value, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqIn(List<Long> values) {
            addCriterion("FUN_SEQ in", values, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqNotIn(List<Long> values) {
            addCriterion("FUN_SEQ not in", values, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqBetween(Long value1, Long value2) {
            addCriterion("FUN_SEQ between", value1, value2, "funSeq");
            return (Criteria) this;
        }

        public Criteria andFunSeqNotBetween(Long value1, Long value2) {
            addCriterion("FUN_SEQ not between", value1, value2, "funSeq");
            return (Criteria) this;
        }

        public Criteria andViewnameIsNull() {
            addCriterion("VIEWNAME is null");
            return (Criteria) this;
        }

        public Criteria andViewnameIsNotNull() {
            addCriterion("VIEWNAME is not null");
            return (Criteria) this;
        }

        public Criteria andViewnameEqualTo(String value) {
            addCriterion("VIEWNAME =", value, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameNotEqualTo(String value) {
            addCriterion("VIEWNAME <>", value, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameGreaterThan(String value) {
            addCriterion("VIEWNAME >", value, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameGreaterThanOrEqualTo(String value) {
            addCriterion("VIEWNAME >=", value, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameLessThan(String value) {
            addCriterion("VIEWNAME <", value, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameLessThanOrEqualTo(String value) {
            addCriterion("VIEWNAME <=", value, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameLike(String value) {
            addCriterion("VIEWNAME like", value, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameNotLike(String value) {
            addCriterion("VIEWNAME not like", value, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameIn(List<String> values) {
            addCriterion("VIEWNAME in", values, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameNotIn(List<String> values) {
            addCriterion("VIEWNAME not in", values, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameBetween(String value1, String value2) {
            addCriterion("VIEWNAME between", value1, value2, "viewname");
            return (Criteria) this;
        }

        public Criteria andViewnameNotBetween(String value1, String value2) {
            addCriterion("VIEWNAME not between", value1, value2, "viewname");
            return (Criteria) this;
        }

        public Criteria andDllPathIsNull() {
            addCriterion("DLL_PATH is null");
            return (Criteria) this;
        }

        public Criteria andDllPathIsNotNull() {
            addCriterion("DLL_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andDllPathEqualTo(String value) {
            addCriterion("DLL_PATH =", value, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathNotEqualTo(String value) {
            addCriterion("DLL_PATH <>", value, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathGreaterThan(String value) {
            addCriterion("DLL_PATH >", value, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathGreaterThanOrEqualTo(String value) {
            addCriterion("DLL_PATH >=", value, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathLessThan(String value) {
            addCriterion("DLL_PATH <", value, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathLessThanOrEqualTo(String value) {
            addCriterion("DLL_PATH <=", value, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathLike(String value) {
            addCriterion("DLL_PATH like", value, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathNotLike(String value) {
            addCriterion("DLL_PATH not like", value, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathIn(List<String> values) {
            addCriterion("DLL_PATH in", values, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathNotIn(List<String> values) {
            addCriterion("DLL_PATH not in", values, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathBetween(String value1, String value2) {
            addCriterion("DLL_PATH between", value1, value2, "dllPath");
            return (Criteria) this;
        }

        public Criteria andDllPathNotBetween(String value1, String value2) {
            addCriterion("DLL_PATH not between", value1, value2, "dllPath");
            return (Criteria) this;
        }

        public Criteria andFuncImgIsNull() {
            addCriterion("FUNC_IMG is null");
            return (Criteria) this;
        }

        public Criteria andFuncImgIsNotNull() {
            addCriterion("FUNC_IMG is not null");
            return (Criteria) this;
        }

        public Criteria andFuncImgEqualTo(String value) {
            addCriterion("FUNC_IMG =", value, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgNotEqualTo(String value) {
            addCriterion("FUNC_IMG <>", value, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgGreaterThan(String value) {
            addCriterion("FUNC_IMG >", value, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgGreaterThanOrEqualTo(String value) {
            addCriterion("FUNC_IMG >=", value, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgLessThan(String value) {
            addCriterion("FUNC_IMG <", value, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgLessThanOrEqualTo(String value) {
            addCriterion("FUNC_IMG <=", value, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgLike(String value) {
            addCriterion("FUNC_IMG like", value, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgNotLike(String value) {
            addCriterion("FUNC_IMG not like", value, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgIn(List<String> values) {
            addCriterion("FUNC_IMG in", values, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgNotIn(List<String> values) {
            addCriterion("FUNC_IMG not in", values, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgBetween(String value1, String value2) {
            addCriterion("FUNC_IMG between", value1, value2, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncImgNotBetween(String value1, String value2) {
            addCriterion("FUNC_IMG not between", value1, value2, "funcImg");
            return (Criteria) this;
        }

        public Criteria andFuncArgIsNull() {
            addCriterion("FUNC_ARG is null");
            return (Criteria) this;
        }

        public Criteria andFuncArgIsNotNull() {
            addCriterion("FUNC_ARG is not null");
            return (Criteria) this;
        }

        public Criteria andFuncArgEqualTo(String value) {
            addCriterion("FUNC_ARG =", value, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgNotEqualTo(String value) {
            addCriterion("FUNC_ARG <>", value, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgGreaterThan(String value) {
            addCriterion("FUNC_ARG >", value, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgGreaterThanOrEqualTo(String value) {
            addCriterion("FUNC_ARG >=", value, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgLessThan(String value) {
            addCriterion("FUNC_ARG <", value, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgLessThanOrEqualTo(String value) {
            addCriterion("FUNC_ARG <=", value, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgLike(String value) {
            addCriterion("FUNC_ARG like", value, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgNotLike(String value) {
            addCriterion("FUNC_ARG not like", value, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgIn(List<String> values) {
            addCriterion("FUNC_ARG in", values, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgNotIn(List<String> values) {
            addCriterion("FUNC_ARG not in", values, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgBetween(String value1, String value2) {
            addCriterion("FUNC_ARG between", value1, value2, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncArgNotBetween(String value1, String value2) {
            addCriterion("FUNC_ARG not between", value1, value2, "funcArg");
            return (Criteria) this;
        }

        public Criteria andFuncTypeIsNull() {
            addCriterion("FUNC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFuncTypeIsNotNull() {
            addCriterion("FUNC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFuncTypeEqualTo(String value) {
            addCriterion("FUNC_TYPE =", value, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeNotEqualTo(String value) {
            addCriterion("FUNC_TYPE <>", value, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeGreaterThan(String value) {
            addCriterion("FUNC_TYPE >", value, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNC_TYPE >=", value, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeLessThan(String value) {
            addCriterion("FUNC_TYPE <", value, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeLessThanOrEqualTo(String value) {
            addCriterion("FUNC_TYPE <=", value, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeLike(String value) {
            addCriterion("FUNC_TYPE like", value, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeNotLike(String value) {
            addCriterion("FUNC_TYPE not like", value, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeIn(List<String> values) {
            addCriterion("FUNC_TYPE in", values, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeNotIn(List<String> values) {
            addCriterion("FUNC_TYPE not in", values, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeBetween(String value1, String value2) {
            addCriterion("FUNC_TYPE between", value1, value2, "funcType");
            return (Criteria) this;
        }

        public Criteria andFuncTypeNotBetween(String value1, String value2) {
            addCriterion("FUNC_TYPE not between", value1, value2, "funcType");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNull() {
            addCriterion("DISABLED is null");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNotNull() {
            addCriterion("DISABLED is not null");
            return (Criteria) this;
        }

        public Criteria andDisabledEqualTo(String value) {
            addCriterion("DISABLED =", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotEqualTo(String value) {
            addCriterion("DISABLED <>", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThan(String value) {
            addCriterion("DISABLED >", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThanOrEqualTo(String value) {
            addCriterion("DISABLED >=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThan(String value) {
            addCriterion("DISABLED <", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThanOrEqualTo(String value) {
            addCriterion("DISABLED <=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLike(String value) {
            addCriterion("DISABLED like", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotLike(String value) {
            addCriterion("DISABLED not like", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledIn(List<String> values) {
            addCriterion("DISABLED in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotIn(List<String> values) {
            addCriterion("DISABLED not in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledBetween(String value1, String value2) {
            addCriterion("DISABLED between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotBetween(String value1, String value2) {
            addCriterion("DISABLED not between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andRecVerIsNull() {
            addCriterion("REC_VER is null");
            return (Criteria) this;
        }

        public Criteria andRecVerIsNotNull() {
            addCriterion("REC_VER is not null");
            return (Criteria) this;
        }

        public Criteria andRecVerEqualTo(Long value) {
            addCriterion("REC_VER =", value, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerNotEqualTo(Long value) {
            addCriterion("REC_VER <>", value, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerGreaterThan(Long value) {
            addCriterion("REC_VER >", value, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerGreaterThanOrEqualTo(Long value) {
            addCriterion("REC_VER >=", value, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerLessThan(Long value) {
            addCriterion("REC_VER <", value, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerLessThanOrEqualTo(Long value) {
            addCriterion("REC_VER <=", value, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerIn(List<Long> values) {
            addCriterion("REC_VER in", values, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerNotIn(List<Long> values) {
            addCriterion("REC_VER not in", values, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerBetween(Long value1, Long value2) {
            addCriterion("REC_VER between", value1, value2, "recVer");
            return (Criteria) this;
        }

        public Criteria andRecVerNotBetween(Long value1, Long value2) {
            addCriterion("REC_VER not between", value1, value2, "recVer");
            return (Criteria) this;
        }

        public Criteria andSysIsNull() {
            addCriterion("SYS is null");
            return (Criteria) this;
        }

        public Criteria andSysIsNotNull() {
            addCriterion("SYS is not null");
            return (Criteria) this;
        }

        public Criteria andSysEqualTo(String value) {
            addCriterion("SYS =", value, "sys");
            return (Criteria) this;
        }

        public Criteria andSysNotEqualTo(String value) {
            addCriterion("SYS <>", value, "sys");
            return (Criteria) this;
        }

        public Criteria andSysGreaterThan(String value) {
            addCriterion("SYS >", value, "sys");
            return (Criteria) this;
        }

        public Criteria andSysGreaterThanOrEqualTo(String value) {
            addCriterion("SYS >=", value, "sys");
            return (Criteria) this;
        }

        public Criteria andSysLessThan(String value) {
            addCriterion("SYS <", value, "sys");
            return (Criteria) this;
        }

        public Criteria andSysLessThanOrEqualTo(String value) {
            addCriterion("SYS <=", value, "sys");
            return (Criteria) this;
        }

        public Criteria andSysLike(String value) {
            addCriterion("SYS like", value, "sys");
            return (Criteria) this;
        }

        public Criteria andSysNotLike(String value) {
            addCriterion("SYS not like", value, "sys");
            return (Criteria) this;
        }

        public Criteria andSysIn(List<String> values) {
            addCriterion("SYS in", values, "sys");
            return (Criteria) this;
        }

        public Criteria andSysNotIn(List<String> values) {
            addCriterion("SYS not in", values, "sys");
            return (Criteria) this;
        }

        public Criteria andSysBetween(String value1, String value2) {
            addCriterion("SYS between", value1, value2, "sys");
            return (Criteria) this;
        }

        public Criteria andSysNotBetween(String value1, String value2) {
            addCriterion("SYS not between", value1, value2, "sys");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("TENANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("TENANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(String value) {
            addCriterion("TENANT_ID =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(String value) {
            addCriterion("TENANT_ID <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(String value) {
            addCriterion("TENANT_ID >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
            addCriterion("TENANT_ID >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(String value) {
            addCriterion("TENANT_ID <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(String value) {
            addCriterion("TENANT_ID <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLike(String value) {
            addCriterion("TENANT_ID like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotLike(String value) {
            addCriterion("TENANT_ID not like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<String> values) {
            addCriterion("TENANT_ID in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<String> values) {
            addCriterion("TENANT_ID not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(String value1, String value2) {
            addCriterion("TENANT_ID between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(String value1, String value2) {
            addCriterion("TENANT_ID not between", value1, value2, "tenantId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table za_function
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 01 14:38:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}