package com.za.pojo;

import java.io.Serializable;
import java.util.Date;

public class ZaFunction implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String funcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.FUNC_CODE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String funcCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.NAME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.PARENT_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.FUNC_LEVEL
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private Long funcLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.FUN_SEQ
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private Long funSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.VIEWNAME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String viewname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.DLL_PATH
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String dllPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.FUNC_IMG
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String funcImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.FUNC_ARG
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String funcArg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.FUNC_TYPE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String funcType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.DISABLED
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String disabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.STATE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private Long recVer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.SYS
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String sys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_function.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.FUNC_ID
     *
     * @return the value of za_function.FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.FUNC_ID
     *
     * @param funcId the value for za_function.FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setFuncId(String funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.FUNC_CODE
     *
     * @return the value of za_function.FUNC_CODE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getFuncCode() {
        return funcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.FUNC_CODE
     *
     * @param funcCode the value for za_function.FUNC_CODE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setFuncCode(String funcCode) {
        this.funcCode = funcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.NAME
     *
     * @return the value of za_function.NAME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.NAME
     *
     * @param name the value for za_function.NAME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.PARENT_ID
     *
     * @return the value of za_function.PARENT_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.PARENT_ID
     *
     * @param parentId the value for za_function.PARENT_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.FUNC_LEVEL
     *
     * @return the value of za_function.FUNC_LEVEL
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public Long getFuncLevel() {
        return funcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.FUNC_LEVEL
     *
     * @param funcLevel the value for za_function.FUNC_LEVEL
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setFuncLevel(Long funcLevel) {
        this.funcLevel = funcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.FUN_SEQ
     *
     * @return the value of za_function.FUN_SEQ
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public Long getFunSeq() {
        return funSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.FUN_SEQ
     *
     * @param funSeq the value for za_function.FUN_SEQ
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setFunSeq(Long funSeq) {
        this.funSeq = funSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.VIEWNAME
     *
     * @return the value of za_function.VIEWNAME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getViewname() {
        return viewname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.VIEWNAME
     *
     * @param viewname the value for za_function.VIEWNAME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setViewname(String viewname) {
        this.viewname = viewname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.DLL_PATH
     *
     * @return the value of za_function.DLL_PATH
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getDllPath() {
        return dllPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.DLL_PATH
     *
     * @param dllPath the value for za_function.DLL_PATH
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setDllPath(String dllPath) {
        this.dllPath = dllPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.FUNC_IMG
     *
     * @return the value of za_function.FUNC_IMG
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getFuncImg() {
        return funcImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.FUNC_IMG
     *
     * @param funcImg the value for za_function.FUNC_IMG
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setFuncImg(String funcImg) {
        this.funcImg = funcImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.FUNC_ARG
     *
     * @return the value of za_function.FUNC_ARG
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getFuncArg() {
        return funcArg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.FUNC_ARG
     *
     * @param funcArg the value for za_function.FUNC_ARG
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setFuncArg(String funcArg) {
        this.funcArg = funcArg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.FUNC_TYPE
     *
     * @return the value of za_function.FUNC_TYPE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getFuncType() {
        return funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.FUNC_TYPE
     *
     * @param funcType the value for za_function.FUNC_TYPE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setFuncType(String funcType) {
        this.funcType = funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.DISABLED
     *
     * @return the value of za_function.DISABLED
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.DISABLED
     *
     * @param disabled the value for za_function.DISABLED
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setDisabled(String disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.STATE
     *
     * @return the value of za_function.STATE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.STATE
     *
     * @param state the value for za_function.STATE
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.REMARKS
     *
     * @return the value of za_function.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.REMARKS
     *
     * @param remarks the value for za_function.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.CREATOR
     *
     * @return the value of za_function.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.CREATOR
     *
     * @param creator the value for za_function.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.CREATE_TIME
     *
     * @return the value of za_function.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.CREATE_TIME
     *
     * @param createTime the value for za_function.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.MODIFIER
     *
     * @return the value of za_function.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.MODIFIER
     *
     * @param modifier the value for za_function.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.MODIFY_TIME
     *
     * @return the value of za_function.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.MODIFY_TIME
     *
     * @param modifyTime the value for za_function.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.REC_VER
     *
     * @return the value of za_function.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public Long getRecVer() {
        return recVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.REC_VER
     *
     * @param recVer the value for za_function.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setRecVer(Long recVer) {
        this.recVer = recVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.SYS
     *
     * @return the value of za_function.SYS
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getSys() {
        return sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.SYS
     *
     * @param sys the value for za_function.SYS
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setSys(String sys) {
        this.sys = sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_function.TENANT_ID
     *
     * @return the value of za_function.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_function.TENANT_ID
     *
     * @param tenantId the value for za_function.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}