package com.za.pojo;

import java.io.Serializable;
import java.util.Date;

public class ZaRoleFunc implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.ROLE_FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String roleFuncId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String funcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Long recVer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role_func.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.ROLE_FUNC_ID
     *
     * @return the value of za_role_func.ROLE_FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getRoleFuncId() {
        return roleFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.ROLE_FUNC_ID
     *
     * @param roleFuncId the value for za_role_func.ROLE_FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRoleFuncId(String roleFuncId) {
        this.roleFuncId = roleFuncId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.ROLE_ID
     *
     * @return the value of za_role_func.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.ROLE_ID
     *
     * @param roleId the value for za_role_func.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.FUNC_ID
     *
     * @return the value of za_role_func.FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.FUNC_ID
     *
     * @param funcId the value for za_role_func.FUNC_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setFuncId(String funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.STATE
     *
     * @return the value of za_role_func.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.STATE
     *
     * @param state the value for za_role_func.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.CREATOR
     *
     * @return the value of za_role_func.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.CREATOR
     *
     * @param creator the value for za_role_func.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.CREATE_TIME
     *
     * @return the value of za_role_func.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.CREATE_TIME
     *
     * @param createTime the value for za_role_func.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.MODIFIER
     *
     * @return the value of za_role_func.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.MODIFIER
     *
     * @param modifier the value for za_role_func.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.MODIFY_TIME
     *
     * @return the value of za_role_func.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.MODIFY_TIME
     *
     * @param modifyTime the value for za_role_func.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.REC_VER
     *
     * @return the value of za_role_func.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Long getRecVer() {
        return recVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.REC_VER
     *
     * @param recVer the value for za_role_func.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRecVer(Long recVer) {
        this.recVer = recVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.TENANT_ID
     *
     * @return the value of za_role_func.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.TENANT_ID
     *
     * @param tenantId the value for za_role_func.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role_func.REMARKS
     *
     * @return the value of za_role_func.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role_func.REMARKS
     *
     * @param remarks the value for za_role_func.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}