package com.za.pojo;

import java.io.Serializable;
import java.util.Date;

public class ZaRole implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.CODE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.NAME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Long recVer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_role.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.ROLE_ID
     *
     * @return the value of za_role.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.ROLE_ID
     *
     * @param roleId the value for za_role.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.CODE
     *
     * @return the value of za_role.CODE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.CODE
     *
     * @param code the value for za_role.CODE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.NAME
     *
     * @return the value of za_role.NAME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.NAME
     *
     * @param name the value for za_role.NAME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.STATE
     *
     * @return the value of za_role.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.STATE
     *
     * @param state the value for za_role.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.REMARKS
     *
     * @return the value of za_role.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.REMARKS
     *
     * @param remarks the value for za_role.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.CREATOR
     *
     * @return the value of za_role.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.CREATOR
     *
     * @param creator the value for za_role.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.CREATE_TIME
     *
     * @return the value of za_role.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.CREATE_TIME
     *
     * @param createTime the value for za_role.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.MODIFIER
     *
     * @return the value of za_role.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.MODIFIER
     *
     * @param modifier the value for za_role.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.MODIFY_TIME
     *
     * @return the value of za_role.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.MODIFY_TIME
     *
     * @param modifyTime the value for za_role.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.REC_VER
     *
     * @return the value of za_role.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Long getRecVer() {
        return recVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.REC_VER
     *
     * @param recVer the value for za_role.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRecVer(Long recVer) {
        this.recVer = recVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_role.TENANT_ID
     *
     * @return the value of za_role.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_role.TENANT_ID
     *
     * @param tenantId the value for za_role.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}