package com.za.pojo;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class ZaUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public ZaUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("USER_ID like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("USER_ID not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("CODE is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("CODE =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("CODE <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("CODE >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CODE >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("CODE <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("CODE <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("CODE like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("CODE not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("CODE in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("CODE not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("CODE between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("CODE not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNull() {
			addCriterion("LOGIN_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLoginNameIsNotNull() {
			addCriterion("LOGIN_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLoginNameEqualTo(String value) {
			addCriterion("LOGIN_NAME =", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotEqualTo(String value) {
			addCriterion("LOGIN_NAME <>", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThan(String value) {
			addCriterion("LOGIN_NAME >", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME >=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThan(String value) {
			addCriterion("LOGIN_NAME <", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLessThanOrEqualTo(String value) {
			addCriterion("LOGIN_NAME <=", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameLike(String value) {
			addCriterion("LOGIN_NAME like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotLike(String value) {
			addCriterion("LOGIN_NAME not like", value, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameIn(List<String> values) {
			addCriterion("LOGIN_NAME in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotIn(List<String> values) {
			addCriterion("LOGIN_NAME not in", values, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andLoginNameNotBetween(String value1, String value2) {
			addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdIsNull() {
			addCriterion("ORGANIZE_ID is null");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdIsNotNull() {
			addCriterion("ORGANIZE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdEqualTo(String value) {
			addCriterion("ORGANIZE_ID =", value, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdNotEqualTo(String value) {
			addCriterion("ORGANIZE_ID <>", value, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdGreaterThan(String value) {
			addCriterion("ORGANIZE_ID >", value, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdGreaterThanOrEqualTo(String value) {
			addCriterion("ORGANIZE_ID >=", value, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdLessThan(String value) {
			addCriterion("ORGANIZE_ID <", value, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdLessThanOrEqualTo(String value) {
			addCriterion("ORGANIZE_ID <=", value, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdLike(String value) {
			addCriterion("ORGANIZE_ID like", value, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdNotLike(String value) {
			addCriterion("ORGANIZE_ID not like", value, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdIn(List<String> values) {
			addCriterion("ORGANIZE_ID in", values, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdNotIn(List<String> values) {
			addCriterion("ORGANIZE_ID not in", values, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdBetween(String value1, String value2) {
			addCriterion("ORGANIZE_ID between", value1, value2, "organizeId");
			return (Criteria) this;
		}

		public Criteria andOrganizeIdNotBetween(String value1, String value2) {
			addCriterion("ORGANIZE_ID not between", value1, value2, "organizeId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdIsNull() {
			addCriterion("REPORT_TO_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdIsNotNull() {
			addCriterion("REPORT_TO_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdEqualTo(Integer value) {
			addCriterion("REPORT_TO_USER_ID =", value, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdNotEqualTo(Integer value) {
			addCriterion("REPORT_TO_USER_ID <>", value, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdGreaterThan(Integer value) {
			addCriterion("REPORT_TO_USER_ID >", value, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("REPORT_TO_USER_ID >=", value, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdLessThan(Integer value) {
			addCriterion("REPORT_TO_USER_ID <", value, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("REPORT_TO_USER_ID <=", value, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdIn(List<Integer> values) {
			addCriterion("REPORT_TO_USER_ID in", values, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdNotIn(List<Integer> values) {
			addCriterion("REPORT_TO_USER_ID not in", values, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdBetween(Integer value1, Integer value2) {
			addCriterion("REPORT_TO_USER_ID between", value1, value2, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andReportToUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("REPORT_TO_USER_ID not between", value1, value2, "reportToUserId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdIsNull() {
			addCriterion("CERTIFI_TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdIsNotNull() {
			addCriterion("CERTIFI_TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdEqualTo(Integer value) {
			addCriterion("CERTIFI_TYPE_ID =", value, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdNotEqualTo(Integer value) {
			addCriterion("CERTIFI_TYPE_ID <>", value, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdGreaterThan(Integer value) {
			addCriterion("CERTIFI_TYPE_ID >", value, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("CERTIFI_TYPE_ID >=", value, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdLessThan(Integer value) {
			addCriterion("CERTIFI_TYPE_ID <", value, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("CERTIFI_TYPE_ID <=", value, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdIn(List<Integer> values) {
			addCriterion("CERTIFI_TYPE_ID in", values, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdNotIn(List<Integer> values) {
			addCriterion("CERTIFI_TYPE_ID not in", values, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("CERTIFI_TYPE_ID between", value1, value2, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("CERTIFI_TYPE_ID not between", value1, value2, "certifiTypeId");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeIsNull() {
			addCriterion("CERTIFI_CODE is null");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeIsNotNull() {
			addCriterion("CERTIFI_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeEqualTo(String value) {
			addCriterion("CERTIFI_CODE =", value, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeNotEqualTo(String value) {
			addCriterion("CERTIFI_CODE <>", value, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeGreaterThan(String value) {
			addCriterion("CERTIFI_CODE >", value, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CERTIFI_CODE >=", value, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeLessThan(String value) {
			addCriterion("CERTIFI_CODE <", value, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeLessThanOrEqualTo(String value) {
			addCriterion("CERTIFI_CODE <=", value, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeLike(String value) {
			addCriterion("CERTIFI_CODE like", value, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeNotLike(String value) {
			addCriterion("CERTIFI_CODE not like", value, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeIn(List<String> values) {
			addCriterion("CERTIFI_CODE in", values, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeNotIn(List<String> values) {
			addCriterion("CERTIFI_CODE not in", values, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeBetween(String value1, String value2) {
			addCriterion("CERTIFI_CODE between", value1, value2, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andCertifiCodeNotBetween(String value1, String value2) {
			addCriterion("CERTIFI_CODE not between", value1, value2, "certifiCode");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("PASSWORD in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("PASSWORD not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordIsNull() {
			addCriterion("ALLOW_CHANGE_PASSWORD is null");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordIsNotNull() {
			addCriterion("ALLOW_CHANGE_PASSWORD is not null");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordEqualTo(String value) {
			addCriterion("ALLOW_CHANGE_PASSWORD =", value, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordNotEqualTo(String value) {
			addCriterion("ALLOW_CHANGE_PASSWORD <>", value, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordGreaterThan(String value) {
			addCriterion("ALLOW_CHANGE_PASSWORD >", value, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordGreaterThanOrEqualTo(String value) {
			addCriterion("ALLOW_CHANGE_PASSWORD >=", value, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordLessThan(String value) {
			addCriterion("ALLOW_CHANGE_PASSWORD <", value, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordLessThanOrEqualTo(String value) {
			addCriterion("ALLOW_CHANGE_PASSWORD <=", value, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordLike(String value) {
			addCriterion("ALLOW_CHANGE_PASSWORD like", value, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordNotLike(String value) {
			addCriterion("ALLOW_CHANGE_PASSWORD not like", value, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordIn(List<String> values) {
			addCriterion("ALLOW_CHANGE_PASSWORD in", values, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordNotIn(List<String> values) {
			addCriterion("ALLOW_CHANGE_PASSWORD not in", values, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordBetween(String value1, String value2) {
			addCriterion("ALLOW_CHANGE_PASSWORD between", value1, value2, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andAllowChangePasswordNotBetween(String value1, String value2) {
			addCriterion("ALLOW_CHANGE_PASSWORD not between", value1, value2, "allowChangePassword");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdIsNull() {
			addCriterion("WORK_TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdIsNotNull() {
			addCriterion("WORK_TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdEqualTo(Integer value) {
			addCriterion("WORK_TYPE_ID =", value, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdNotEqualTo(Integer value) {
			addCriterion("WORK_TYPE_ID <>", value, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdGreaterThan(Integer value) {
			addCriterion("WORK_TYPE_ID >", value, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("WORK_TYPE_ID >=", value, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdLessThan(Integer value) {
			addCriterion("WORK_TYPE_ID <", value, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("WORK_TYPE_ID <=", value, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdIn(List<Integer> values) {
			addCriterion("WORK_TYPE_ID in", values, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdNotIn(List<Integer> values) {
			addCriterion("WORK_TYPE_ID not in", values, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("WORK_TYPE_ID between", value1, value2, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andWorkTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("WORK_TYPE_ID not between", value1, value2, "workTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdIsNull() {
			addCriterion("USER_TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdIsNotNull() {
			addCriterion("USER_TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdEqualTo(Integer value) {
			addCriterion("USER_TYPE_ID =", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdNotEqualTo(Integer value) {
			addCriterion("USER_TYPE_ID <>", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdGreaterThan(Integer value) {
			addCriterion("USER_TYPE_ID >", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("USER_TYPE_ID >=", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdLessThan(Integer value) {
			addCriterion("USER_TYPE_ID <", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("USER_TYPE_ID <=", value, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdIn(List<Integer> values) {
			addCriterion("USER_TYPE_ID in", values, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdNotIn(List<Integer> values) {
			addCriterion("USER_TYPE_ID not in", values, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("USER_TYPE_ID between", value1, value2, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andUserTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("USER_TYPE_ID not between", value1, value2, "userTypeId");
			return (Criteria) this;
		}

		public Criteria andCheckFlagIsNull() {
			addCriterion("CHECK_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andCheckFlagIsNotNull() {
			addCriterion("CHECK_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andCheckFlagEqualTo(String value) {
			addCriterion("CHECK_FLAG =", value, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagNotEqualTo(String value) {
			addCriterion("CHECK_FLAG <>", value, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagGreaterThan(String value) {
			addCriterion("CHECK_FLAG >", value, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagGreaterThanOrEqualTo(String value) {
			addCriterion("CHECK_FLAG >=", value, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagLessThan(String value) {
			addCriterion("CHECK_FLAG <", value, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagLessThanOrEqualTo(String value) {
			addCriterion("CHECK_FLAG <=", value, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagLike(String value) {
			addCriterion("CHECK_FLAG like", value, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagNotLike(String value) {
			addCriterion("CHECK_FLAG not like", value, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagIn(List<String> values) {
			addCriterion("CHECK_FLAG in", values, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagNotIn(List<String> values) {
			addCriterion("CHECK_FLAG not in", values, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagBetween(String value1, String value2) {
			addCriterion("CHECK_FLAG between", value1, value2, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andCheckFlagNotBetween(String value1, String value2) {
			addCriterion("CHECK_FLAG not between", value1, value2, "checkFlag");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdIsNull() {
			addCriterion("EDUCATION_TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdIsNotNull() {
			addCriterion("EDUCATION_TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdEqualTo(Integer value) {
			addCriterion("EDUCATION_TYPE_ID =", value, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdNotEqualTo(Integer value) {
			addCriterion("EDUCATION_TYPE_ID <>", value, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdGreaterThan(Integer value) {
			addCriterion("EDUCATION_TYPE_ID >", value, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("EDUCATION_TYPE_ID >=", value, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdLessThan(Integer value) {
			addCriterion("EDUCATION_TYPE_ID <", value, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdLessThanOrEqualTo(Integer value) {
			addCriterion("EDUCATION_TYPE_ID <=", value, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdIn(List<Integer> values) {
			addCriterion("EDUCATION_TYPE_ID in", values, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdNotIn(List<Integer> values) {
			addCriterion("EDUCATION_TYPE_ID not in", values, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdBetween(Integer value1, Integer value2) {
			addCriterion("EDUCATION_TYPE_ID between", value1, value2, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andEducationTypeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("EDUCATION_TYPE_ID not between", value1, value2, "educationTypeId");
			return (Criteria) this;
		}

		public Criteria andHomeTelIsNull() {
			addCriterion("HOME_TEL is null");
			return (Criteria) this;
		}

		public Criteria andHomeTelIsNotNull() {
			addCriterion("HOME_TEL is not null");
			return (Criteria) this;
		}

		public Criteria andHomeTelEqualTo(String value) {
			addCriterion("HOME_TEL =", value, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelNotEqualTo(String value) {
			addCriterion("HOME_TEL <>", value, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelGreaterThan(String value) {
			addCriterion("HOME_TEL >", value, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelGreaterThanOrEqualTo(String value) {
			addCriterion("HOME_TEL >=", value, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelLessThan(String value) {
			addCriterion("HOME_TEL <", value, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelLessThanOrEqualTo(String value) {
			addCriterion("HOME_TEL <=", value, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelLike(String value) {
			addCriterion("HOME_TEL like", value, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelNotLike(String value) {
			addCriterion("HOME_TEL not like", value, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelIn(List<String> values) {
			addCriterion("HOME_TEL in", values, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelNotIn(List<String> values) {
			addCriterion("HOME_TEL not in", values, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelBetween(String value1, String value2) {
			addCriterion("HOME_TEL between", value1, value2, "homeTel");
			return (Criteria) this;
		}

		public Criteria andHomeTelNotBetween(String value1, String value2) {
			addCriterion("HOME_TEL not between", value1, value2, "homeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelIsNull() {
			addCriterion("OFFICE_TEL is null");
			return (Criteria) this;
		}

		public Criteria andOfficeTelIsNotNull() {
			addCriterion("OFFICE_TEL is not null");
			return (Criteria) this;
		}

		public Criteria andOfficeTelEqualTo(String value) {
			addCriterion("OFFICE_TEL =", value, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelNotEqualTo(String value) {
			addCriterion("OFFICE_TEL <>", value, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelGreaterThan(String value) {
			addCriterion("OFFICE_TEL >", value, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelGreaterThanOrEqualTo(String value) {
			addCriterion("OFFICE_TEL >=", value, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelLessThan(String value) {
			addCriterion("OFFICE_TEL <", value, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelLessThanOrEqualTo(String value) {
			addCriterion("OFFICE_TEL <=", value, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelLike(String value) {
			addCriterion("OFFICE_TEL like", value, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelNotLike(String value) {
			addCriterion("OFFICE_TEL not like", value, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelIn(List<String> values) {
			addCriterion("OFFICE_TEL in", values, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelNotIn(List<String> values) {
			addCriterion("OFFICE_TEL not in", values, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelBetween(String value1, String value2) {
			addCriterion("OFFICE_TEL between", value1, value2, "officeTel");
			return (Criteria) this;
		}

		public Criteria andOfficeTelNotBetween(String value1, String value2) {
			addCriterion("OFFICE_TEL not between", value1, value2, "officeTel");
			return (Criteria) this;
		}

		public Criteria andMobileTeleIsNull() {
			addCriterion("MOBILE_TELE is null");
			return (Criteria) this;
		}

		public Criteria andMobileTeleIsNotNull() {
			addCriterion("MOBILE_TELE is not null");
			return (Criteria) this;
		}

		public Criteria andMobileTeleEqualTo(String value) {
			addCriterion("MOBILE_TELE =", value, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleNotEqualTo(String value) {
			addCriterion("MOBILE_TELE <>", value, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleGreaterThan(String value) {
			addCriterion("MOBILE_TELE >", value, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleGreaterThanOrEqualTo(String value) {
			addCriterion("MOBILE_TELE >=", value, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleLessThan(String value) {
			addCriterion("MOBILE_TELE <", value, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleLessThanOrEqualTo(String value) {
			addCriterion("MOBILE_TELE <=", value, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleLike(String value) {
			addCriterion("MOBILE_TELE like", value, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleNotLike(String value) {
			addCriterion("MOBILE_TELE not like", value, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleIn(List<String> values) {
			addCriterion("MOBILE_TELE in", values, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleNotIn(List<String> values) {
			addCriterion("MOBILE_TELE not in", values, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleBetween(String value1, String value2) {
			addCriterion("MOBILE_TELE between", value1, value2, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andMobileTeleNotBetween(String value1, String value2) {
			addCriterion("MOBILE_TELE not between", value1, value2, "mobileTele");
			return (Criteria) this;
		}

		public Criteria andAddrIdIsNull() {
			addCriterion("ADDR_ID is null");
			return (Criteria) this;
		}

		public Criteria andAddrIdIsNotNull() {
			addCriterion("ADDR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAddrIdEqualTo(String value) {
			addCriterion("ADDR_ID =", value, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdNotEqualTo(String value) {
			addCriterion("ADDR_ID <>", value, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdGreaterThan(String value) {
			addCriterion("ADDR_ID >", value, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdGreaterThanOrEqualTo(String value) {
			addCriterion("ADDR_ID >=", value, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdLessThan(String value) {
			addCriterion("ADDR_ID <", value, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdLessThanOrEqualTo(String value) {
			addCriterion("ADDR_ID <=", value, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdLike(String value) {
			addCriterion("ADDR_ID like", value, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdNotLike(String value) {
			addCriterion("ADDR_ID not like", value, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdIn(List<String> values) {
			addCriterion("ADDR_ID in", values, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdNotIn(List<String> values) {
			addCriterion("ADDR_ID not in", values, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdBetween(String value1, String value2) {
			addCriterion("ADDR_ID between", value1, value2, "addrId");
			return (Criteria) this;
		}

		public Criteria andAddrIdNotBetween(String value1, String value2) {
			addCriterion("ADDR_ID not between", value1, value2, "addrId");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateIsNull() {
			addCriterion("EFFECT_DATE is null");
			return (Criteria) this;
		}

		public Criteria andEffectDateIsNotNull() {
			addCriterion("EFFECT_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andEffectDateEqualTo(Date value) {
			addCriterion("EFFECT_DATE =", value, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateNotEqualTo(Date value) {
			addCriterion("EFFECT_DATE <>", value, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateGreaterThan(Date value) {
			addCriterion("EFFECT_DATE >", value, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateGreaterThanOrEqualTo(Date value) {
			addCriterion("EFFECT_DATE >=", value, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateLessThan(Date value) {
			addCriterion("EFFECT_DATE <", value, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateLessThanOrEqualTo(Date value) {
			addCriterion("EFFECT_DATE <=", value, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateIn(List<Date> values) {
			addCriterion("EFFECT_DATE in", values, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateNotIn(List<Date> values) {
			addCriterion("EFFECT_DATE not in", values, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateBetween(Date value1, Date value2) {
			addCriterion("EFFECT_DATE between", value1, value2, "effectDate");
			return (Criteria) this;
		}

		public Criteria andEffectDateNotBetween(Date value1, Date value2) {
			addCriterion("EFFECT_DATE not between", value1, value2, "effectDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateIsNull() {
			addCriterion("EXPIRE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andExpireDateIsNotNull() {
			addCriterion("EXPIRE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andExpireDateEqualTo(Date value) {
			addCriterion("EXPIRE_DATE =", value, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateNotEqualTo(Date value) {
			addCriterion("EXPIRE_DATE <>", value, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateGreaterThan(Date value) {
			addCriterion("EXPIRE_DATE >", value, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateGreaterThanOrEqualTo(Date value) {
			addCriterion("EXPIRE_DATE >=", value, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateLessThan(Date value) {
			addCriterion("EXPIRE_DATE <", value, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateLessThanOrEqualTo(Date value) {
			addCriterion("EXPIRE_DATE <=", value, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateIn(List<Date> values) {
			addCriterion("EXPIRE_DATE in", values, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateNotIn(List<Date> values) {
			addCriterion("EXPIRE_DATE not in", values, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateBetween(Date value1, Date value2) {
			addCriterion("EXPIRE_DATE between", value1, value2, "expireDate");
			return (Criteria) this;
		}

		public Criteria andExpireDateNotBetween(Date value1, Date value2) {
			addCriterion("EXPIRE_DATE not between", value1, value2, "expireDate");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagIsNull() {
			addCriterion("MULTI_LOGIN_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagIsNotNull() {
			addCriterion("MULTI_LOGIN_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagEqualTo(Short value) {
			addCriterion("MULTI_LOGIN_FLAG =", value, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagNotEqualTo(Short value) {
			addCriterion("MULTI_LOGIN_FLAG <>", value, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagGreaterThan(Short value) {
			addCriterion("MULTI_LOGIN_FLAG >", value, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagGreaterThanOrEqualTo(Short value) {
			addCriterion("MULTI_LOGIN_FLAG >=", value, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagLessThan(Short value) {
			addCriterion("MULTI_LOGIN_FLAG <", value, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagLessThanOrEqualTo(Short value) {
			addCriterion("MULTI_LOGIN_FLAG <=", value, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagIn(List<Short> values) {
			addCriterion("MULTI_LOGIN_FLAG in", values, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagNotIn(List<Short> values) {
			addCriterion("MULTI_LOGIN_FLAG not in", values, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagBetween(Short value1, Short value2) {
			addCriterion("MULTI_LOGIN_FLAG between", value1, value2, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andMultiLoginFlagNotBetween(Short value1, Short value2) {
			addCriterion("MULTI_LOGIN_FLAG not between", value1, value2, "multiLoginFlag");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdIsNull() {
			addCriterion("LAST_LOGIN_LOG_ID is null");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdIsNotNull() {
			addCriterion("LAST_LOGIN_LOG_ID is not null");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdEqualTo(Long value) {
			addCriterion("LAST_LOGIN_LOG_ID =", value, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdNotEqualTo(Long value) {
			addCriterion("LAST_LOGIN_LOG_ID <>", value, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdGreaterThan(Long value) {
			addCriterion("LAST_LOGIN_LOG_ID >", value, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdGreaterThanOrEqualTo(Long value) {
			addCriterion("LAST_LOGIN_LOG_ID >=", value, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdLessThan(Long value) {
			addCriterion("LAST_LOGIN_LOG_ID <", value, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdLessThanOrEqualTo(Long value) {
			addCriterion("LAST_LOGIN_LOG_ID <=", value, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdIn(List<Long> values) {
			addCriterion("LAST_LOGIN_LOG_ID in", values, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdNotIn(List<Long> values) {
			addCriterion("LAST_LOGIN_LOG_ID not in", values, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdBetween(Long value1, Long value2) {
			addCriterion("LAST_LOGIN_LOG_ID between", value1, value2, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andLastLoginLogIdNotBetween(Long value1, Long value2) {
			addCriterion("LAST_LOGIN_LOG_ID not between", value1, value2, "lastLoginLogId");
			return (Criteria) this;
		}

		public Criteria andTryTimesIsNull() {
			addCriterion("TRY_TIMES is null");
			return (Criteria) this;
		}

		public Criteria andTryTimesIsNotNull() {
			addCriterion("TRY_TIMES is not null");
			return (Criteria) this;
		}

		public Criteria andTryTimesEqualTo(Long value) {
			addCriterion("TRY_TIMES =", value, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesNotEqualTo(Long value) {
			addCriterion("TRY_TIMES <>", value, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesGreaterThan(Long value) {
			addCriterion("TRY_TIMES >", value, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesGreaterThanOrEqualTo(Long value) {
			addCriterion("TRY_TIMES >=", value, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesLessThan(Long value) {
			addCriterion("TRY_TIMES <", value, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesLessThanOrEqualTo(Long value) {
			addCriterion("TRY_TIMES <=", value, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesIn(List<Long> values) {
			addCriterion("TRY_TIMES in", values, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesNotIn(List<Long> values) {
			addCriterion("TRY_TIMES not in", values, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesBetween(Long value1, Long value2) {
			addCriterion("TRY_TIMES between", value1, value2, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andTryTimesNotBetween(Long value1, Long value2) {
			addCriterion("TRY_TIMES not between", value1, value2, "tryTimes");
			return (Criteria) this;
		}

		public Criteria andLockFlagIsNull() {
			addCriterion("LOCK_FLAG is null");
			return (Criteria) this;
		}

		public Criteria andLockFlagIsNotNull() {
			addCriterion("LOCK_FLAG is not null");
			return (Criteria) this;
		}

		public Criteria andLockFlagEqualTo(String value) {
			addCriterion("LOCK_FLAG =", value, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagNotEqualTo(String value) {
			addCriterion("LOCK_FLAG <>", value, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagGreaterThan(String value) {
			addCriterion("LOCK_FLAG >", value, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagGreaterThanOrEqualTo(String value) {
			addCriterion("LOCK_FLAG >=", value, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagLessThan(String value) {
			addCriterion("LOCK_FLAG <", value, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagLessThanOrEqualTo(String value) {
			addCriterion("LOCK_FLAG <=", value, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagLike(String value) {
			addCriterion("LOCK_FLAG like", value, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagNotLike(String value) {
			addCriterion("LOCK_FLAG not like", value, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagIn(List<String> values) {
			addCriterion("LOCK_FLAG in", values, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagNotIn(List<String> values) {
			addCriterion("LOCK_FLAG not in", values, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagBetween(String value1, String value2) {
			addCriterion("LOCK_FLAG between", value1, value2, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andLockFlagNotBetween(String value1, String value2) {
			addCriterion("LOCK_FLAG not between", value1, value2, "lockFlag");
			return (Criteria) this;
		}

		public Criteria andIsLoginIsNull() {
			addCriterion("IS_LOGIN is null");
			return (Criteria) this;
		}

		public Criteria andIsLoginIsNotNull() {
			addCriterion("IS_LOGIN is not null");
			return (Criteria) this;
		}

		public Criteria andIsLoginEqualTo(String value) {
			addCriterion("IS_LOGIN =", value, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginNotEqualTo(String value) {
			addCriterion("IS_LOGIN <>", value, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginGreaterThan(String value) {
			addCriterion("IS_LOGIN >", value, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginGreaterThanOrEqualTo(String value) {
			addCriterion("IS_LOGIN >=", value, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginLessThan(String value) {
			addCriterion("IS_LOGIN <", value, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginLessThanOrEqualTo(String value) {
			addCriterion("IS_LOGIN <=", value, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginLike(String value) {
			addCriterion("IS_LOGIN like", value, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginNotLike(String value) {
			addCriterion("IS_LOGIN not like", value, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginIn(List<String> values) {
			addCriterion("IS_LOGIN in", values, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginNotIn(List<String> values) {
			addCriterion("IS_LOGIN not in", values, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginBetween(String value1, String value2) {
			addCriterion("IS_LOGIN between", value1, value2, "isLogin");
			return (Criteria) this;
		}

		public Criteria andIsLoginNotBetween(String value1, String value2) {
			addCriterion("IS_LOGIN not between", value1, value2, "isLogin");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("STATE is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("STATE is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("STATE =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("STATE <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("STATE >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("STATE >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("STATE <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("STATE <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("STATE like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("STATE not like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<String> values) {
			addCriterion("STATE in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<String> values) {
			addCriterion("STATE not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("STATE between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("STATE not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNull() {
			addCriterion("CREATOR is null");
			return (Criteria) this;
		}

		public Criteria andCreatorIsNotNull() {
			addCriterion("CREATOR is not null");
			return (Criteria) this;
		}

		public Criteria andCreatorEqualTo(String value) {
			addCriterion("CREATOR =", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotEqualTo(String value) {
			addCriterion("CREATOR <>", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThan(String value) {
			addCriterion("CREATOR >", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorGreaterThanOrEqualTo(String value) {
			addCriterion("CREATOR >=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThan(String value) {
			addCriterion("CREATOR <", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLessThanOrEqualTo(String value) {
			addCriterion("CREATOR <=", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorLike(String value) {
			addCriterion("CREATOR like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotLike(String value) {
			addCriterion("CREATOR not like", value, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorIn(List<String> values) {
			addCriterion("CREATOR in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotIn(List<String> values) {
			addCriterion("CREATOR not in", values, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorBetween(String value1, String value2) {
			addCriterion("CREATOR between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreatorNotBetween(String value1, String value2) {
			addCriterion("CREATOR not between", value1, value2, "creator");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andModifierIsNull() {
			addCriterion("MODIFIER is null");
			return (Criteria) this;
		}

		public Criteria andModifierIsNotNull() {
			addCriterion("MODIFIER is not null");
			return (Criteria) this;
		}

		public Criteria andModifierEqualTo(String value) {
			addCriterion("MODIFIER =", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotEqualTo(String value) {
			addCriterion("MODIFIER <>", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThan(String value) {
			addCriterion("MODIFIER >", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFIER >=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThan(String value) {
			addCriterion("MODIFIER <", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLessThanOrEqualTo(String value) {
			addCriterion("MODIFIER <=", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierLike(String value) {
			addCriterion("MODIFIER like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotLike(String value) {
			addCriterion("MODIFIER not like", value, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierIn(List<String> values) {
			addCriterion("MODIFIER in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotIn(List<String> values) {
			addCriterion("MODIFIER not in", values, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierBetween(String value1, String value2) {
			addCriterion("MODIFIER between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifierNotBetween(String value1, String value2) {
			addCriterion("MODIFIER not between", value1, value2, "modifier");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andRecVerIsNull() {
			addCriterion("REC_VER is null");
			return (Criteria) this;
		}

		public Criteria andRecVerIsNotNull() {
			addCriterion("REC_VER is not null");
			return (Criteria) this;
		}

		public Criteria andRecVerEqualTo(Long value) {
			addCriterion("REC_VER =", value, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerNotEqualTo(Long value) {
			addCriterion("REC_VER <>", value, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerGreaterThan(Long value) {
			addCriterion("REC_VER >", value, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerGreaterThanOrEqualTo(Long value) {
			addCriterion("REC_VER >=", value, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerLessThan(Long value) {
			addCriterion("REC_VER <", value, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerLessThanOrEqualTo(Long value) {
			addCriterion("REC_VER <=", value, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerIn(List<Long> values) {
			addCriterion("REC_VER in", values, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerNotIn(List<Long> values) {
			addCriterion("REC_VER not in", values, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerBetween(Long value1, Long value2) {
			addCriterion("REC_VER between", value1, value2, "recVer");
			return (Criteria) this;
		}

		public Criteria andRecVerNotBetween(Long value1, Long value2) {
			addCriterion("REC_VER not between", value1, value2, "recVer");
			return (Criteria) this;
		}

		public Criteria andQqIsNull() {
			addCriterion("QQ is null");
			return (Criteria) this;
		}

		public Criteria andQqIsNotNull() {
			addCriterion("QQ is not null");
			return (Criteria) this;
		}

		public Criteria andQqEqualTo(String value) {
			addCriterion("QQ =", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotEqualTo(String value) {
			addCriterion("QQ <>", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThan(String value) {
			addCriterion("QQ >", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqGreaterThanOrEqualTo(String value) {
			addCriterion("QQ >=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThan(String value) {
			addCriterion("QQ <", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLessThanOrEqualTo(String value) {
			addCriterion("QQ <=", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqLike(String value) {
			addCriterion("QQ like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotLike(String value) {
			addCriterion("QQ not like", value, "qq");
			return (Criteria) this;
		}

		public Criteria andQqIn(List<String> values) {
			addCriterion("QQ in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotIn(List<String> values) {
			addCriterion("QQ not in", values, "qq");
			return (Criteria) this;
		}

		public Criteria andQqBetween(String value1, String value2) {
			addCriterion("QQ between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andQqNotBetween(String value1, String value2) {
			addCriterion("QQ not between", value1, value2, "qq");
			return (Criteria) this;
		}

		public Criteria andIconIsNull() {
			addCriterion("ICON is null");
			return (Criteria) this;
		}

		public Criteria andIconIsNotNull() {
			addCriterion("ICON is not null");
			return (Criteria) this;
		}

		public Criteria andIconEqualTo(String value) {
			addCriterion("ICON =", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotEqualTo(String value) {
			addCriterion("ICON <>", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconGreaterThan(String value) {
			addCriterion("ICON >", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconGreaterThanOrEqualTo(String value) {
			addCriterion("ICON >=", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLessThan(String value) {
			addCriterion("ICON <", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLessThanOrEqualTo(String value) {
			addCriterion("ICON <=", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLike(String value) {
			addCriterion("ICON like", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotLike(String value) {
			addCriterion("ICON not like", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconIn(List<String> values) {
			addCriterion("ICON in", values, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotIn(List<String> values) {
			addCriterion("ICON not in", values, "icon");
			return (Criteria) this;
		}

		public Criteria andIconBetween(String value1, String value2) {
			addCriterion("ICON between", value1, value2, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotBetween(String value1, String value2) {
			addCriterion("ICON not between", value1, value2, "icon");
			return (Criteria) this;
		}

		public Criteria andIconSmallIsNull() {
			addCriterion("ICON_SMALL is null");
			return (Criteria) this;
		}

		public Criteria andIconSmallIsNotNull() {
			addCriterion("ICON_SMALL is not null");
			return (Criteria) this;
		}

		public Criteria andIconSmallEqualTo(String value) {
			addCriterion("ICON_SMALL =", value, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallNotEqualTo(String value) {
			addCriterion("ICON_SMALL <>", value, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallGreaterThan(String value) {
			addCriterion("ICON_SMALL >", value, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallGreaterThanOrEqualTo(String value) {
			addCriterion("ICON_SMALL >=", value, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallLessThan(String value) {
			addCriterion("ICON_SMALL <", value, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallLessThanOrEqualTo(String value) {
			addCriterion("ICON_SMALL <=", value, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallLike(String value) {
			addCriterion("ICON_SMALL like", value, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallNotLike(String value) {
			addCriterion("ICON_SMALL not like", value, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallIn(List<String> values) {
			addCriterion("ICON_SMALL in", values, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallNotIn(List<String> values) {
			addCriterion("ICON_SMALL not in", values, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallBetween(String value1, String value2) {
			addCriterion("ICON_SMALL between", value1, value2, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andIconSmallNotBetween(String value1, String value2) {
			addCriterion("ICON_SMALL not between", value1, value2, "iconSmall");
			return (Criteria) this;
		}

		public Criteria andMsnIsNull() {
			addCriterion("MSN is null");
			return (Criteria) this;
		}

		public Criteria andMsnIsNotNull() {
			addCriterion("MSN is not null");
			return (Criteria) this;
		}

		public Criteria andMsnEqualTo(String value) {
			addCriterion("MSN =", value, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnNotEqualTo(String value) {
			addCriterion("MSN <>", value, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnGreaterThan(String value) {
			addCriterion("MSN >", value, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnGreaterThanOrEqualTo(String value) {
			addCriterion("MSN >=", value, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnLessThan(String value) {
			addCriterion("MSN <", value, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnLessThanOrEqualTo(String value) {
			addCriterion("MSN <=", value, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnLike(String value) {
			addCriterion("MSN like", value, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnNotLike(String value) {
			addCriterion("MSN not like", value, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnIn(List<String> values) {
			addCriterion("MSN in", values, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnNotIn(List<String> values) {
			addCriterion("MSN not in", values, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnBetween(String value1, String value2) {
			addCriterion("MSN between", value1, value2, "msn");
			return (Criteria) this;
		}

		public Criteria andMsnNotBetween(String value1, String value2) {
			addCriterion("MSN not between", value1, value2, "msn");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusIsNull() {
			addCriterion("ONLINE_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusIsNotNull() {
			addCriterion("ONLINE_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusEqualTo(String value) {
			addCriterion("ONLINE_STATUS =", value, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusNotEqualTo(String value) {
			addCriterion("ONLINE_STATUS <>", value, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusGreaterThan(String value) {
			addCriterion("ONLINE_STATUS >", value, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusGreaterThanOrEqualTo(String value) {
			addCriterion("ONLINE_STATUS >=", value, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusLessThan(String value) {
			addCriterion("ONLINE_STATUS <", value, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusLessThanOrEqualTo(String value) {
			addCriterion("ONLINE_STATUS <=", value, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusLike(String value) {
			addCriterion("ONLINE_STATUS like", value, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusNotLike(String value) {
			addCriterion("ONLINE_STATUS not like", value, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusIn(List<String> values) {
			addCriterion("ONLINE_STATUS in", values, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusNotIn(List<String> values) {
			addCriterion("ONLINE_STATUS not in", values, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusBetween(String value1, String value2) {
			addCriterion("ONLINE_STATUS between", value1, value2, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andOnlineStatusNotBetween(String value1, String value2) {
			addCriterion("ONLINE_STATUS not between", value1, value2, "onlineStatus");
			return (Criteria) this;
		}

		public Criteria andUnitsIdIsNull() {
			addCriterion("UNITS_ID is null");
			return (Criteria) this;
		}

		public Criteria andUnitsIdIsNotNull() {
			addCriterion("UNITS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUnitsIdEqualTo(String value) {
			addCriterion("UNITS_ID =", value, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdNotEqualTo(String value) {
			addCriterion("UNITS_ID <>", value, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdGreaterThan(String value) {
			addCriterion("UNITS_ID >", value, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdGreaterThanOrEqualTo(String value) {
			addCriterion("UNITS_ID >=", value, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdLessThan(String value) {
			addCriterion("UNITS_ID <", value, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdLessThanOrEqualTo(String value) {
			addCriterion("UNITS_ID <=", value, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdLike(String value) {
			addCriterion("UNITS_ID like", value, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdNotLike(String value) {
			addCriterion("UNITS_ID not like", value, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdIn(List<String> values) {
			addCriterion("UNITS_ID in", values, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdNotIn(List<String> values) {
			addCriterion("UNITS_ID not in", values, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdBetween(String value1, String value2) {
			addCriterion("UNITS_ID between", value1, value2, "unitsId");
			return (Criteria) this;
		}

		public Criteria andUnitsIdNotBetween(String value1, String value2) {
			addCriterion("UNITS_ID not between", value1, value2, "unitsId");
			return (Criteria) this;
		}

		public Criteria andIssendmsgIsNull() {
			addCriterion("ISSENDMSG is null");
			return (Criteria) this;
		}

		public Criteria andIssendmsgIsNotNull() {
			addCriterion("ISSENDMSG is not null");
			return (Criteria) this;
		}

		public Criteria andIssendmsgEqualTo(String value) {
			addCriterion("ISSENDMSG =", value, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgNotEqualTo(String value) {
			addCriterion("ISSENDMSG <>", value, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgGreaterThan(String value) {
			addCriterion("ISSENDMSG >", value, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgGreaterThanOrEqualTo(String value) {
			addCriterion("ISSENDMSG >=", value, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgLessThan(String value) {
			addCriterion("ISSENDMSG <", value, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgLessThanOrEqualTo(String value) {
			addCriterion("ISSENDMSG <=", value, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgLike(String value) {
			addCriterion("ISSENDMSG like", value, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgNotLike(String value) {
			addCriterion("ISSENDMSG not like", value, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgIn(List<String> values) {
			addCriterion("ISSENDMSG in", values, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgNotIn(List<String> values) {
			addCriterion("ISSENDMSG not in", values, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgBetween(String value1, String value2) {
			addCriterion("ISSENDMSG between", value1, value2, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andIssendmsgNotBetween(String value1, String value2) {
			addCriterion("ISSENDMSG not between", value1, value2, "issendmsg");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNull() {
			addCriterion("TENANT_ID is null");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNotNull() {
			addCriterion("TENANT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTenantIdEqualTo(String value) {
			addCriterion("TENANT_ID =", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotEqualTo(String value) {
			addCriterion("TENANT_ID <>", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThan(String value) {
			addCriterion("TENANT_ID >", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
			addCriterion("TENANT_ID >=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThan(String value) {
			addCriterion("TENANT_ID <", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThanOrEqualTo(String value) {
			addCriterion("TENANT_ID <=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLike(String value) {
			addCriterion("TENANT_ID like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotLike(String value) {
			addCriterion("TENANT_ID not like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIn(List<String> values) {
			addCriterion("TENANT_ID in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotIn(List<String> values) {
			addCriterion("TENANT_ID not in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdBetween(String value1, String value2) {
			addCriterion("TENANT_ID between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotBetween(String value1, String value2) {
			addCriterion("TENANT_ID not between", value1, value2, "tenantId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table za_user
     *
     * @mbg.generated do_not_delete_during_merge Sun Jul 01 00:21:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}