package com.za.pojo;

import java.io.Serializable;
import java.util.Date;

public class ZaUserRole implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.ROLE_USER_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String roleUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.USER_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private Long recVer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column za_user_role.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.ROLE_USER_ID
     *
     * @return the value of za_user_role.ROLE_USER_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getRoleUserId() {
        return roleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.ROLE_USER_ID
     *
     * @param roleUserId the value for za_user_role.ROLE_USER_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRoleUserId(String roleUserId) {
        this.roleUserId = roleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.USER_ID
     *
     * @return the value of za_user_role.USER_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.USER_ID
     *
     * @param userId the value for za_user_role.USER_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.ROLE_ID
     *
     * @return the value of za_user_role.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.ROLE_ID
     *
     * @param roleId the value for za_user_role.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.STATE
     *
     * @return the value of za_user_role.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.STATE
     *
     * @param state the value for za_user_role.STATE
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.CREATOR
     *
     * @return the value of za_user_role.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.CREATOR
     *
     * @param creator the value for za_user_role.CREATOR
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.CREATE_TIME
     *
     * @return the value of za_user_role.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.CREATE_TIME
     *
     * @param createTime the value for za_user_role.CREATE_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.MODIFIER
     *
     * @return the value of za_user_role.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.MODIFIER
     *
     * @param modifier the value for za_user_role.MODIFIER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.MODIFY_TIME
     *
     * @return the value of za_user_role.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.MODIFY_TIME
     *
     * @param modifyTime the value for za_user_role.MODIFY_TIME
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.REC_VER
     *
     * @return the value of za_user_role.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public Long getRecVer() {
        return recVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.REC_VER
     *
     * @param recVer the value for za_user_role.REC_VER
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRecVer(Long recVer) {
        this.recVer = recVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.TENANT_ID
     *
     * @return the value of za_user_role.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.TENANT_ID
     *
     * @param tenantId the value for za_user_role.TENANT_ID
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column za_user_role.REMARKS
     *
     * @return the value of za_user_role.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column za_user_role.REMARKS
     *
     * @param remarks the value for za_user_role.REMARKS
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}