package com.za.api.dao;

import com.za.pojo.ZaFunction;
import com.za.pojo.ZaFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZaFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    long countByExample(ZaFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    int deleteByExample(ZaFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    int deleteByPrimaryKey(String funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    int insert(ZaFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    int insertSelective(ZaFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    List<ZaFunction> selectByExample(ZaFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    ZaFunction selectByPrimaryKey(String funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZaFunction record, @Param("example") ZaFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    int updateByExample(@Param("record") ZaFunction record, @Param("example") ZaFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    int updateByPrimaryKeySelective(ZaFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_function
     *
     * @mbg.generated Sun Jul 01 14:38:11 CST 2018
     */
    int updateByPrimaryKey(ZaFunction record);
}