package com.za.api.dao;

import com.za.pojo.ZaRoleFunc;
import com.za.pojo.ZaRoleFuncExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZaRoleFuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    long countByExample(ZaRoleFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int deleteByExample(ZaRoleFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int insert(ZaRoleFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int insertSelective(ZaRoleFunc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    List<ZaRoleFunc> selectByExampleWithBLOBs(ZaRoleFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    List<ZaRoleFunc> selectByExample(ZaRoleFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZaRoleFunc record, @Param("example") ZaRoleFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ZaRoleFunc record, @Param("example") ZaRoleFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_role_func
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int updateByExample(@Param("record") ZaRoleFunc record, @Param("example") ZaRoleFuncExample example);
}