package com.za.api.dao;

import com.za.pojo.ZaUser;
import com.za.pojo.ZaUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZaUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	long countByExample(ZaUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int deleteByExample(ZaUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int insert(ZaUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int insertSelective(ZaUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	List<ZaUser> selectByExampleWithBLOBs(ZaUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	List<ZaUser> selectByExample(ZaUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	ZaUser selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int updateByExampleSelective(@Param("record") ZaUser record, @Param("example") ZaUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") ZaUser record, @Param("example") ZaUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int updateByExample(@Param("record") ZaUser record, @Param("example") ZaUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int updateByPrimaryKeySelective(ZaUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(ZaUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table za_user
	 * @mbg.generated  Sun Jul 01 13:16:41 CST 2018
	 */
	int updateByPrimaryKey(ZaUser record);
}