package com.za.api.dao;

import com.za.pojo.ZaUserRole;
import com.za.pojo.ZaUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZaUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    long countByExample(ZaUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int deleteByExample(ZaUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int insert(ZaUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int insertSelective(ZaUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    List<ZaUserRole> selectByExampleWithBLOBs(ZaUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    List<ZaUserRole> selectByExample(ZaUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") ZaUserRole record, @Param("example") ZaUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ZaUserRole record, @Param("example") ZaUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table za_user_role
     *
     * @mbg.generated Sun Jul 01 14:34:01 CST 2018
     */
    int updateByExample(@Param("record") ZaUserRole record, @Param("example") ZaUserRoleExample example);
}